export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';


export const  COUNTER_PLUS = 'COUNTER_PLUS'
export const  COUNTER_MINUS= 'COUNTER_MINUS'

export const  ADD_LIST= 'ADD_LIST'
export const  SUM_COUNTER= 'SUM_COUNTER'
export const  SHOW_COUNTER='SHOW_COUNTER'
export const  DELETE_LIST_ALL='DELETE_LIST_ALL'
export const  DELETE_LIST_INDEX='DELETE_LIST_INDEX'